/* loc.h — compile-time language selection for stud_sys TUI.
 *
 * Default language is Polish. Build with `make LANG=EN` to switch to English.
 * Add a new language by defining LANG_<XX> in the makefile and a matching
 * block below. Keep all user-facing literals here; sources should reference
 * only the L_* macros.
 */
#ifndef STUD_SYS_LOC_H
#define STUD_SYS_LOC_H

#if defined(LANG_EN)

/* ===== Budzik / Alarm ===== */
#define L_BUDZ_MAIN_TITLE    " ALARM: <Ent> - silence signal; <Esc> - dismiss "
#define L_BUDZ_REPORTED      "     Set for %02d:%02d"
#define L_BUDZ_NEXT_PING     "     Next ping in %dmin.%02dsec."
#define L_BUDZ_PROMPT_INT    " %s [%d-%d]: %-8s  (Enter=confirm  Esc=cancel)"
#define L_BUDZ_PROMPT_TXT    " %s: %-44s  (Enter=confirm  Esc=cancel)"
#define L_BUDZ_FIELD_NAME    "  Subject : %.52s"
#define L_BUDZ_FIELD_TIME    "  Time    : %02d:%02d"
#define L_BUDZ_FIELD_EVERY   "  Every   : %d min  (lead: %d min)"
#define L_BUDZ_ASK_NAME      "Alarm name"
#define L_BUDZ_ASK_HOUR      "Hour"
#define L_BUDZ_ASK_MIN       "Minute"
#define L_BUDZ_ASK_EVERY     "Every N minutes"
#define L_BUDZ_ASK_LEAD      "Lead time [min]"
#define L_BUDZ_LIST_TITLE    " ALARM LIST "
#define L_BUDZ_NEW_TITLE     " NEW ALARM "
#define L_BUDZ_EDIT_TITLE    " ALARM "
#define L_BUDZ_MENU_SAVE_NEW "  >>> Save to agenda <<<"
#define L_BUDZ_MENU_CANCEL   "  Cancel"
#define L_BUDZ_MENU_APPLY    "  >>> Apply changes <<<"
#define L_BUDZ_MENU_DELETE   "  >>> Delete alarm <<<"
#define L_BUDZ_MENU_EXIT_NC  "  Exit (no changes)"
#define L_BUDZ_MENU_ADD      "  +++ Add new alarm +++"
#define L_BUDZ_MENU_EXIT     "  Exit"
#define L_BUDZ_AGENDA_TITLE  " Alarm list "

/* ===== Core (main menu, login, agenda form, queue) ===== */
#define L_CORE_MODE_GRAPH         "Switch to GRAPHICAL mode"
#define L_CORE_MODE_TEXT          "Switch to TEXT mode      "
#define L_CORE_MAIN_MENU_TITLE    " MAIN MENU "
#define L_CORE_DEFAULT_ALARM_NAME " Alarm %d"
#define L_CORE_ERR_DEF_REPORT     " def_Report failed for service %d (%s). <Ent> "
#define L_CORE_HDR_SUBSYSTEM      " SUBSYSTEM"
#define L_CORE_VERSION_BANNER     "      STUD_SYS version 1.0"
#define L_CORE_USER_LABEL         "      User: "
#define L_CORE_ERR_AGENDA_FULL    " No room in AGENDA for %s <ENT> "
#define L_CORE_ERR_NO_MEM_ORDER   " Out of memory for order %s <Ent> "
#define L_CORE_ERR_QUEUE_FULL     " No room in QUEUE for %s <ENT> "
#define L_CORE_ERR_ADDR_MISMATCH  " Address mismatch %s "
#define L_CORE_MENU_LAUNCH_NEW    "Yes - launch new"
#define L_CORE_MENU_NO            "No"
#define L_CORE_INFO_NOT_IN_AGENDA " No %s in agenda "
#define L_CORE_TITLE_LAUNCH_NEW   " Launch new? "
#define L_CORE_FORM_SERVICE_TYPE  "* Service type <%s> "
#define L_CORE_STATUS_SKIP        " skip if previous still queued"
#define L_CORE_STATUS_ALWAYS      " always enter queue (run old and new)"
#define L_CORE_STATUS_REPLACE     " enter queue and replace previously queued "
#define L_CORE_FORM_ORDER_STATUS  "+ Order status: "
#define L_CORE_TYP_PERM           "p permanent (always on)"
#define L_CORE_TYP_SERIAL         "s serial"
#define L_CORE_TYP_ONESHOT        "t one-shot"
#define L_CORE_TYP_PROMPT         "?  ENTER TYPE !!!!! "
#define L_CORE_FORM_PRIORITY      "+ Priority (%d-%d)  ?? "
#define L_CORE_FORM_PRIO_GROWTH   "+ Priority growth per 1sec wait (%d-%d)  ?? "
#define L_CORE_FORM_CYCLE_PERIOD  "+ Call cycle period [sec] (%d-%d)  ?? "
#define L_CORE_FORM_NEXT_CALL     " Seconds to next call  ??"
#define L_CORE_INFO_PERMANENT     " Permanent service "
#define L_CORE_INFO_CANCELLED     " SERVICE CANCELLED !!!!! "
#define L_CORE_FORM_NUM_CALLS     " Number of calls  ??"
#define L_CORE_FORM_CALLS_LEFT    " Calls remaining  "
#define L_CORE_RUN_DATA           "d data"
#define L_CORE_RUN_NEXT           "n next"
#define L_CORE_RUN_LIST           "l list"
#define L_CORE_RUN_MAIN_MENU      "m main menu"
#define L_CORE_RUN_DELETE         "u DELETE"
#define L_CORE_RUN_ENTER          "w ADD to agenda"
#define L_CORE_FORM_WHAT_NEXT     " What next <%s>  ?? "
#define L_CORE_YES_SHORT          "t yes"
#define L_CORE_NO_SHORT           "n no"
#define L_CORE_FORM_LAUNCH_NEW    " Launch new  <%s> ?? "
#define L_CORE_INFO_NO_ALARMS     " No alarms in agenda "
#define L_CORE_LIST_ROW           " %19S type=%c prio=%d count=%d times"
#define L_CORE_ERR_OPEN_FILE      "File open error"
#define L_CORE_TITLE_ERROR        " ERROR"

#else /* LANG_PL — default */

/* ===== Budzik ===== */
#define L_BUDZ_MAIN_TITLE    " BUDZIK: <Ent> - wylaczenie sygnalu; <Esc> - usuniecie monitu "
#define L_BUDZ_REPORTED      "     Zgloszono na godz.%02d.%02d"
#define L_BUDZ_NEXT_PING     "     Najblizszy monit za %dmin.%02dsek."
#define L_BUDZ_PROMPT_INT    " %s [%d-%d]: %-8s  (Enter=zatwierdz  Esc=anuluj)"
#define L_BUDZ_PROMPT_TXT    " %s: %-44s  (Enter=zatwierdz  Esc=anuluj)"
#define L_BUDZ_FIELD_NAME    "  Sprawa  : %.52s"
#define L_BUDZ_FIELD_TIME    "  Godzina : %02d:%02d"
#define L_BUDZ_FIELD_EVERY   "  Co ile  : %d min  (wyprzedz: %d min)"
#define L_BUDZ_ASK_NAME      "Nazwa budzika"
#define L_BUDZ_ASK_HOUR      "Godzina"
#define L_BUDZ_ASK_MIN       "Minuta"
#define L_BUDZ_ASK_EVERY     "Co ile minut"
#define L_BUDZ_ASK_LEAD      "Wyprzedzenie [min]"
#define L_BUDZ_LIST_TITLE    " LISTA BUDZIKOW "
#define L_BUDZ_NEW_TITLE     " NOWY BUDZIK "
#define L_BUDZ_EDIT_TITLE    " BUDZIK "
#define L_BUDZ_MENU_SAVE_NEW "  >>> Wpisz do agendy <<<"
#define L_BUDZ_MENU_CANCEL   "  Anuluj"
#define L_BUDZ_MENU_APPLY    "  >>> Zatwierdz zmiany <<<"
#define L_BUDZ_MENU_DELETE   "  >>> Usun budzik <<<"
#define L_BUDZ_MENU_EXIT_NC  "  Wyjdz (bez zmian)"
#define L_BUDZ_MENU_ADD      "  +++ Dodaj nowy budzik +++"
#define L_BUDZ_MENU_EXIT     "  Wyjdz"
#define L_BUDZ_AGENDA_TITLE  " Lista budzikow "

/* ===== Core (menu glowne, logowanie, formularz agendy, kolejka) ===== */
#define L_CORE_MODE_GRAPH         "Zmiana trybu na GRAFICZNY"
#define L_CORE_MODE_TEXT          "Zmiana trybu na TEKSTOWY "
#define L_CORE_MAIN_MENU_TITLE    " MENU GLOWNE "
#define L_CORE_DEFAULT_ALARM_NAME " Budzik %d"
#define L_CORE_ERR_DEF_REPORT     " Blad def_Report dla uslugi %d (%s). <Ent> "
#define L_CORE_HDR_SUBSYSTEM      " PODSYSTEM"
#define L_CORE_VERSION_BANNER     "      STUD_SYS wersja 1.0"
#define L_CORE_USER_LABEL         "      Uzytkownik: "
#define L_CORE_ERR_AGENDA_FULL    " Brak miejsca w AGENDZIE na %s <ENT> "
#define L_CORE_ERR_NO_MEM_ORDER   " Brak pamieci dla zlecenia %s <Ent> "
#define L_CORE_ERR_QUEUE_FULL     " Brak miejsca w KOLEJCE na %s <ENT> "
#define L_CORE_ERR_ADDR_MISMATCH  " Niespojnosc adsresow %s "
#define L_CORE_MENU_LAUNCH_NEW    "Tak - uruchom nowy"
#define L_CORE_MENU_NO            "Nie"
#define L_CORE_INFO_NOT_IN_AGENDA " Brak %s w agendzie "
#define L_CORE_TITLE_LAUNCH_NEW   " Uruchomic nowe? "
#define L_CORE_FORM_SERVICE_TYPE  "* Typ uslugi <%s> "
#define L_CORE_STATUS_SKIP        " nie wchodzi gdy poprzednie jest jeszcze w kolejce"
#define L_CORE_STATUS_ALWAYS      " wchodzi zawsze do kolejki (wykonuje sie stare i nowe)"
#define L_CORE_STATUS_REPLACE     " wchodzi do kolejki i usuwa poprzednio wstawione "
#define L_CORE_FORM_ORDER_STATUS  "+ Status zlecenia: "
#define L_CORE_TYP_PERM           "p permanentna (stala)"
#define L_CORE_TYP_SERIAL         "s seryjna"
#define L_CORE_TYP_ONESHOT        "t dorazna"
#define L_CORE_TYP_PROMPT         "?  WPISZ TYP !!!!! "
#define L_CORE_FORM_PRIORITY      "+ Priorytet (%d-%d)  ?? "
#define L_CORE_FORM_PRIO_GROWTH   "+ Przyrost prioryt.po 1sek. oczekiwania (%d-%d)  ?? "
#define L_CORE_FORM_CYCLE_PERIOD  "+ Okres cyku wywolan [sek] (%d-%d)  ?? "
#define L_CORE_FORM_NEXT_CALL     " Liczba sek.do najblizszego wywolania  ??"
#define L_CORE_INFO_PERMANENT     " Usluga stala "
#define L_CORE_INFO_CANCELLED     " USLUGA ANULOWANA !!!!! "
#define L_CORE_FORM_NUM_CALLS     " Liczba wywolan  ??"
#define L_CORE_FORM_CALLS_LEFT    " Pozostalo wywolan  "
#define L_CORE_RUN_DATA           "d dane"
#define L_CORE_RUN_NEXT           "n nastepny"
#define L_CORE_RUN_LIST           "l lista"
#define L_CORE_RUN_MAIN_MENU      "m menu glowne"
#define L_CORE_RUN_DELETE         "u USUNAC"
#define L_CORE_RUN_ENTER          "w WPIS do agendy"
#define L_CORE_FORM_WHAT_NEXT     " Co dalej <%s>  ?? "
#define L_CORE_YES_SHORT          "t tak"
#define L_CORE_NO_SHORT           "n nie"
#define L_CORE_FORM_LAUNCH_NEW    " Uruchomic nowe  <%s> ?? "
#define L_CORE_INFO_NO_ALARMS     " Brak budzikow w agendzie "
#define L_CORE_LIST_ROW           " %19S typ=%c prio=%d krotn=%d razy"
#define L_CORE_ERR_OPEN_FILE      "Blad otwarcia pliku"
#define L_CORE_TITLE_ERROR        " BLAD"

#endif

#endif /* STUD_SYS_LOC_H */
