/* loc.h — compile-time language selection for stud_sys TUI.
 *
 * Default language is Polish. Build with `make LANG=EN` to switch to English.
 * Add a new language by defining LANG_<XX> in the makefile and a matching
 * block below. Keep all user-facing literals here; sources should reference
 * only the L_* macros.
 */
#ifndef STUD_SYS_LOC_H
#define STUD_SYS_LOC_H

#if defined(LANG_EN)

/* ===== Budzik / Alarm ===== */
#define L_BUDZ_MAIN_TITLE    " ALARM: <Ent> - silence signal; <Esc> - dismiss "
#define L_BUDZ_REPORTED      "     Set for %02d:%02d"
#define L_BUDZ_NEXT_PING     "     Next ping in %dmin.%02dsec."
#define L_BUDZ_PROMPT_INT    " %s [%d-%d]: %-8s  (Enter=confirm  Esc=cancel)"
#define L_BUDZ_PROMPT_TXT    " %s: %-44s  (Enter=confirm  Esc=cancel)"
#define L_BUDZ_FIELD_NAME    "  Subject : %.52s"
#define L_BUDZ_FIELD_TIME    "  Time    : %02d:%02d"
#define L_BUDZ_FIELD_EVERY   "  Every   : %d min  (lead: %d min)"
#define L_BUDZ_ASK_NAME      "Alarm name"
#define L_BUDZ_ASK_HOUR      "Hour"
#define L_BUDZ_ASK_MIN       "Minute"
#define L_BUDZ_ASK_EVERY     "Every N minutes"
#define L_BUDZ_ASK_LEAD      "Lead time [min]"
#define L_BUDZ_LIST_TITLE    " ALARM LIST "
#define L_BUDZ_NEW_TITLE     " NEW ALARM "
#define L_BUDZ_EDIT_TITLE    " ALARM "
#define L_BUDZ_MENU_SAVE_NEW "  >>> Save to agenda <<<"
#define L_BUDZ_MENU_CANCEL   "  Cancel"
#define L_BUDZ_MENU_APPLY    "  >>> Apply changes <<<"
#define L_BUDZ_MENU_DELETE   "  >>> Delete alarm <<<"
#define L_BUDZ_MENU_EXIT_NC  "  Exit (no changes)"
#define L_BUDZ_MENU_ADD      "  +++ Add new alarm +++"
#define L_BUDZ_MENU_EXIT     "  Exit"
#define L_BUDZ_AGENDA_TITLE  " Alarm list "

/* ===== Core (main menu, login, agenda form, queue) ===== */
#define L_CORE_MODE_GRAPH         "Switch to GRAPHICAL mode"
#define L_CORE_MODE_TEXT          "Switch to TEXT mode      "
#define L_CORE_MAIN_MENU_TITLE    " MAIN MENU "
#define L_CORE_DEFAULT_ALARM_NAME " Alarm %d"
#define L_CORE_ERR_DEF_REPORT     " def_Report failed for service %d (%s). <Ent> "
#define L_CORE_HDR_SUBSYSTEM      " SUBSYSTEM"
#define L_CORE_VERSION_BANNER     "      STUD_SYS version 1.0"
#define L_CORE_USER_LABEL         "      User: "
#define L_CORE_ERR_AGENDA_FULL    " No room in AGENDA for %s <ENT> "
#define L_CORE_ERR_NO_MEM_ORDER   " Out of memory for order %s <Ent> "
#define L_CORE_ERR_QUEUE_FULL     " No room in QUEUE for %s <ENT> "
#define L_CORE_ERR_ADDR_MISMATCH  " Address mismatch %s "
#define L_CORE_MENU_LAUNCH_NEW    "Yes - launch new"
#define L_CORE_MENU_NO            "No"
#define L_CORE_INFO_NOT_IN_AGENDA " No %s in agenda "
#define L_CORE_TITLE_LAUNCH_NEW   " Launch new? "
#define L_CORE_FORM_SERVICE_TYPE  "* Service type <%s> "
#define L_CORE_STATUS_SKIP        " skip if previous still queued"
#define L_CORE_STATUS_ALWAYS      " always enter queue (run old and new)"
#define L_CORE_STATUS_REPLACE     " enter queue and replace previously queued "
#define L_CORE_FORM_ORDER_STATUS  "+ Order status: "
#define L_CORE_TYP_PERM           "p permanent (always on)"
#define L_CORE_TYP_SERIAL         "s serial"
#define L_CORE_TYP_ONESHOT        "t one-shot"
#define L_CORE_TYP_PROMPT         "?  ENTER TYPE !!!!! "
#define L_CORE_FORM_PRIORITY      "+ Priority (%d-%d)  ?? "
#define L_CORE_FORM_PRIO_GROWTH   "+ Priority growth per 1sec wait (%d-%d)  ?? "
#define L_CORE_FORM_CYCLE_PERIOD  "+ Call cycle period [sec] (%d-%d)  ?? "
#define L_CORE_FORM_NEXT_CALL     " Seconds to next call  ??"
#define L_CORE_INFO_PERMANENT     " Permanent service "
#define L_CORE_INFO_CANCELLED     " SERVICE CANCELLED !!!!! "
#define L_CORE_FORM_NUM_CALLS     " Number of calls  ??"
#define L_CORE_FORM_CALLS_LEFT    " Calls remaining  "
#define L_CORE_RUN_DATA           "d data"
#define L_CORE_RUN_NEXT           "n next"
#define L_CORE_RUN_LIST           "l list"
#define L_CORE_RUN_MAIN_MENU      "m main menu"
#define L_CORE_RUN_DELETE         "u DELETE"
#define L_CORE_RUN_ENTER          "w ADD to agenda"
#define L_CORE_FORM_WHAT_NEXT     " What next <%s>  ?? "
#define L_CORE_YES_SHORT          "t yes"
#define L_CORE_NO_SHORT           "n no"
#define L_CORE_FORM_LAUNCH_NEW    " Launch new  <%s> ?? "
#define L_CORE_INFO_NO_ALARMS     " No alarms in agenda "
#define L_CORE_LIST_ROW           " %19S type=%c prio=%d count=%d times"
#define L_CORE_ERR_OPEN_FILE      "File open error"
#define L_CORE_TITLE_ERROR        " ERROR"

/* ===== Admin module ===== */
#define L_ADMIN_ERR_ADDR_MISMATCH " Address mismatch in RAP_ZM(d=%p dp=%p). <Ent> "
#define L_ADMIN_MENU_BROWSE_LOG   "Browse log.dat file"
#define L_ADMIN_MENU_SYS_INFO     "System info"
#define L_ADMIN_MENU_TITLE        " SELECT OPTION "
#define L_ADMIN_ERR_LOG_OPEN      "+ Log open error: %s"
#define L_ADMIN_LOG_HEADER        "+ --- Log: %s ---"
#define L_ADMIN_SYS_INFO_TITLE    "+ System info"
#define L_ADMIN_SYS_INFO_LINE     "+ System: Linux/Unix (ncurses)"

/* ===== Agenda reports (sprawdz / sys_rap) ===== */
#define L_RAP_DATE_PREFIX         " Date %02d.%02d.%02d "
#define L_RAP_TIME_FMT            "Time %02d:%02d.%02d (%s)"
#define L_RAP_DAY_SUNDAY          "Sunday"
#define L_RAP_DAY_MONDAY          "Monday"
#define L_RAP_DAY_TUESDAY         "Tuesday"
#define L_RAP_DAY_WEDNESDAY       "Wednesday"
#define L_RAP_DAY_THURSDAY        "Thursday"
#define L_RAP_DAY_FRIDAY          "Friday"
#define L_RAP_DAY_SATURDAY        "Saturday"
#define L_RAP_ERR_ADDR_SPRAWDZ    " Address error in Sprawdz (A=%p). <Ent> "
#define L_RAP_TITLE_BASIC         "+ Basic order report SPRAWDZ (total %d)"
#define L_RAP_NO_ORDER_AT_POS     "+ No order at pos.%d in agenda"
#define L_RAP_MAIN_ORDER          "+ Main order:"
#define L_RAP_LIST_ROW_PRIOR      " %19S type=%c prior=%d period=%d"
#define L_RAP_TYP_USL_NO_PREFIX   " Service type <%s> "
#define L_RAP_PERMANENT_NOREM     "+   Permanent order, not removable !!!! "
#define L_RAP_PERIOD_BR           " Call period [sec](%d-%d) ?? "
#define L_RAP_TIME_TO_NEXT        " Time to next call %dmin %dsec"
#define L_RAP_PRIORITY            " Priority (%d-%d) ?? "
#define L_RAP_STATE_PROGRESS      " Execution state "
#define L_RAP_MENU_DATA_ENTRY     "d enter data"
#define L_RAP_MENU_ALG_DATA       "a algorithm data"
#define L_RAP_MENU_DELETE         "u delete"
#define L_RAP_PROMPT_ACTION       " What now <%s>  ?? "
#define L_RAP_NO_RECORD_SYS       " No record in RAP_SYS no=%d. <Ent> "
#define L_RAP_NO_ORDERS_AGENDA    " No orders in agenda "
#define L_RAP_TITLE_PERIODIC      "+ Periodic order report in agenda (total %d)"
#define L_RAP_ORDER_RANGE         "+ Order (%d-%d) "
#define L_RAP_SERVICE_LINE        "+ Service: %19s type=%c prior=%d Cycle=%d Delay=%5.0f"
#define L_RAP_PERMANENT_SHORT     "  Permanent order !! "
#define L_RAP_NUM_CALLS           " Number of calls  "
#define L_RAP_PERIOD_BR_QQ        " Call period (%d-%d)  ?? "

/* ===== Konfig (service / subsystem menu names) ===== */
#define L_KONFIG_SRV_SPRAWDZ      " Env. check"
#define L_KONFIG_SRV_BUDZIK       " Alarm"
#define L_KONFIG_SRV_ADMIN        " About system..."
#define L_KONFIG_SRV_MQTT         " MQTT Publisher"
#define L_KONFIG_SRV_SENSOR       " Sim sensor"
#define L_KONFIG_SRV_STAN         " -- System status --"

/* ===== Sensor sim ===== */
#define L_SIM_WAVE_SINE           "Sine"
#define L_SIM_WAVE_SQUARE         "Square"
#define L_SIM_WAVE_SAW            "Saw"
#define L_SIM_WAVE_NOISE          "Noise"
#define L_SIM_SERVICE_NAME        "simulated sensor"
#define L_SIM_LIVE_READONLY       "+ Live preview (read-only)"
#define L_SIM_HEADER              "+ ===== Simulated sensor ====="
#define L_SIM_VALUE               "+  Value    : %d"
#define L_SIM_VALUE2              "+  Value2   : %s"
#define L_SIM_VALUE3              "+  Value3   : %10.4f"
#define L_SIM_MIN_MAX             "+  Min/Max  : %10.4f / %10.4f"
#define L_SIM_SAMPLES             "+  Samples  : %.0f"
#define L_SIM_ALARM_LABEL         "+  Alarm    : %s"
#define L_SIM_ALARM_OK            "OK"
#define L_SIM_ALARM_RANGE         "RANGE !!!"
#define L_SIM_ALARM_TIME          "TIME !!!"
#define L_SIM_FIELD_WAVE          "+ Waveform        "
#define L_SIM_FIELD_AMP           "+ Amplitude       "
#define L_SIM_FIELD_FREQ          "+ Frequency       "
#define L_SIM_FIELD_OFFS          "+ DC offset       "
#define L_SIM_FIELD_TMAX          "+ Alarm thr MAX   "
#define L_SIM_FIELD_TMIN          "+ Alarm thr MIN   "
#define L_SIM_LIST_TITLE          " Sensor list "

/* ===== MQTT Publisher ===== */
#define L_MQTT_MENU_CONNECT       "  >>> Connect / Save <<<"
#define L_MQTT_MENU_DISCONNECT    "  >>> Disconnect      <<<"
#define L_MQTT_TITLE              " MQTT PUBLISHER "
#define L_MQTT_STATUS_LINE        "  Status   : %s  (pub:%d  err:%d)"
#define L_MQTT_STATE_CONNECTED    "CONNECTED"
#define L_MQTT_STATE_DISCONNECTED "Disconnected"
#define L_MQTT_FIELD_BROKER       "  Broker   : %s"
#define L_MQTT_FIELD_PORT         "  Port     : %d"
#define L_MQTT_FIELD_TOPIC        "  Topic    : %s"
#define L_MQTT_FIELD_NODE_ID      "  Node ID  : %d"
#define L_MQTT_FIELD_QOS          "  QoS      : %d"
#define L_MQTT_FIELD_INTERVAL     "  Interval : %d s"
#define L_MQTT_PROMPT_BROKER      "Broker"
#define L_MQTT_PROMPT_PORT        "Port"
#define L_MQTT_PROMPT_TOPIC       "Topic"
#define L_MQTT_PROMPT_NODE_ID     "Node ID"
#define L_MQTT_PROMPT_QOS         "QoS"
#define L_MQTT_PROMPT_INTERVAL    "Interval [s]"
#define L_MQTT_OK_MSG             " Connected to %s:%d  (topic: %s/%d/...)"
#define L_MQTT_ERR_MSG            " Connection error to %s:%d  (err: %d) <Ent>"

/* ===== Wewy (form engine: passwords, session start, common errors) ===== */
/* Password / permission flow */
#define L_WEWY_SAVE_OR_CANCEL    "  <Ent> - save data; <Esc> - discard changes: ??     "
#define L_WEWY_ENTER_PASSWORD    " ENTER PASSWORD and confirm with <Ent>: ?? "
#define L_WEWY_BAD_PASSWORD_1    " WRONG PASSWORD: <Ent> - retry; <Esc> - exit discarding changes: ??  "
#define L_WEWY_BAD_PASSWORD_2    " WRONG PASSWORD: <Ent> - retry; <Esc> - exit procedure: ??   "
#define L_WEWY_LOW_PERMS_1       "  PERMISSIONS TOO LOW: <Ent> - retry; <Esc> - exit discarding changes ?? "
#define L_WEWY_LOW_PERMS_2       "PERMISSIONS TOO LOW: <Ent> - retry; <Esc> - exit discarding changes: ?? "
#define L_WEWY_NEED_MAIN_TERM    " Permission level %d requires MAIN TERMINAL !! <Ent> "
#define L_WEWY_ONLY_MAIN_TERM    " Changes only allowed from MAIN TERMINAL !! Will be DISCARDED. <Ent> "
#define L_WEWY_ASK_PERM_CODE     " Enter permission code [%s] ?? "
/* Permission level labels */
#define L_WEWY_PERM_0            "0 view only"
#define L_WEWY_PERM_1            "1 write from main term"
#define L_WEWY_PERM_2            "2 write with password"
#define L_WEWY_PERM_3            "3 main term + password"
#define L_WEWY_PERM_4            "4 main operator"
#define L_WEWY_PERM_5            "5 main operator + main term"
/* Session startup */
#define L_WEWY_PREV_REPORTS_OPEN " Reports from previous session not closed    <Ent>    "
#define L_WEWY_PREV_ALLOCS_LEFT  " Memory allocations from previous session left (%d) <Ent>  "
#define L_WEWY_NEW_ALLOCS_SESS   " New memory allocations this session: was %d now %d <Ent>  "
#define L_WEWY_PREV_BLANKS_OPEN  "Unclosed blankets (last %d, state %d) from previous session: <q> - quit; <d> - continue ?? "
#define L_WEWY_PREV_REPORT_OPEN  "Unclosed report %d from previous session: <q> - quit; <d> - continue ?? "
/* Common runtime errors */
#define L_WEWY_NO_DATA_GENERIC   " No data !! "
#define L_WEWY_NO_REPORT_DATA    " No data for report %d !!!!!!!!!!!!!!! <Ent> "
#define L_WEWY_NO_REPORT         " No report %d !!!!!!!!!!!!!!! <Ent> "
#define L_WEWY_NO_REPORTS_OPEN   " No reports open. Use otworz_raporty() !!!!!  <Ent>    "
#define L_WEWY_REPORT_NO_FREE    " Report %d not freeing memory - alloc %s(%d) not possible "
#define L_WEWY_ALL_REPORTS       " ALL REPORTS !!!!!!!   "
/* Input markers / prompts */
#define L_WEWY_ENTER_REPLY       "Enter reply to the previous question"
#define L_WEWY_ABORT_PROMPT      "   ABORT program !!! ?? YES - 't'     "
#define L_WEWY_OUT_OF_RANGE      " OUT OF RANGE !! <ENT>-fix "
#define L_WEWY_OUT_OF            " out of "
#define L_WEWY_OUT_OF_FMT        " out of%s <ENT> "
#define L_WEWY_MISSING_MARK      " !? "
#define L_WEWY_MISSING_LONG      " Missing !! "
#define L_WEWY_DATA_ENTRY        "  Data entry "
#define L_WEWY_BAD_DATA          "Bad data (%s) of type %c"
#define L_WEWY_NO_SYNC_TASK      " No task synchronized with keyboard !!! <q - exit> "

#else /* LANG_PL — default */

/* ===== Budzik ===== */
#define L_BUDZ_MAIN_TITLE    " BUDZIK: <Ent> - wylaczenie sygnalu; <Esc> - usuniecie monitu "
#define L_BUDZ_REPORTED      "     Zgloszono na godz.%02d.%02d"
#define L_BUDZ_NEXT_PING     "     Najblizszy monit za %dmin.%02dsek."
#define L_BUDZ_PROMPT_INT    " %s [%d-%d]: %-8s  (Enter=zatwierdz  Esc=anuluj)"
#define L_BUDZ_PROMPT_TXT    " %s: %-44s  (Enter=zatwierdz  Esc=anuluj)"
#define L_BUDZ_FIELD_NAME    "  Sprawa  : %.52s"
#define L_BUDZ_FIELD_TIME    "  Godzina : %02d:%02d"
#define L_BUDZ_FIELD_EVERY   "  Co ile  : %d min  (wyprzedz: %d min)"
#define L_BUDZ_ASK_NAME      "Nazwa budzika"
#define L_BUDZ_ASK_HOUR      "Godzina"
#define L_BUDZ_ASK_MIN       "Minuta"
#define L_BUDZ_ASK_EVERY     "Co ile minut"
#define L_BUDZ_ASK_LEAD      "Wyprzedzenie [min]"
#define L_BUDZ_LIST_TITLE    " LISTA BUDZIKOW "
#define L_BUDZ_NEW_TITLE     " NOWY BUDZIK "
#define L_BUDZ_EDIT_TITLE    " BUDZIK "
#define L_BUDZ_MENU_SAVE_NEW "  >>> Wpisz do agendy <<<"
#define L_BUDZ_MENU_CANCEL   "  Anuluj"
#define L_BUDZ_MENU_APPLY    "  >>> Zatwierdz zmiany <<<"
#define L_BUDZ_MENU_DELETE   "  >>> Usun budzik <<<"
#define L_BUDZ_MENU_EXIT_NC  "  Wyjdz (bez zmian)"
#define L_BUDZ_MENU_ADD      "  +++ Dodaj nowy budzik +++"
#define L_BUDZ_MENU_EXIT     "  Wyjdz"
#define L_BUDZ_AGENDA_TITLE  " Lista budzikow "

/* ===== Core (menu glowne, logowanie, formularz agendy, kolejka) ===== */
#define L_CORE_MODE_GRAPH         "Zmiana trybu na GRAFICZNY"
#define L_CORE_MODE_TEXT          "Zmiana trybu na TEKSTOWY "
#define L_CORE_MAIN_MENU_TITLE    " MENU GLOWNE "
#define L_CORE_DEFAULT_ALARM_NAME " Budzik %d"
#define L_CORE_ERR_DEF_REPORT     " Blad def_Report dla uslugi %d (%s). <Ent> "
#define L_CORE_HDR_SUBSYSTEM      " PODSYSTEM"
#define L_CORE_VERSION_BANNER     "      STUD_SYS wersja 1.0"
#define L_CORE_USER_LABEL         "      Uzytkownik: "
#define L_CORE_ERR_AGENDA_FULL    " Brak miejsca w AGENDZIE na %s <ENT> "
#define L_CORE_ERR_NO_MEM_ORDER   " Brak pamieci dla zlecenia %s <Ent> "
#define L_CORE_ERR_QUEUE_FULL     " Brak miejsca w KOLEJCE na %s <ENT> "
#define L_CORE_ERR_ADDR_MISMATCH  " Niespojnosc adsresow %s "
#define L_CORE_MENU_LAUNCH_NEW    "Tak - uruchom nowy"
#define L_CORE_MENU_NO            "Nie"
#define L_CORE_INFO_NOT_IN_AGENDA " Brak %s w agendzie "
#define L_CORE_TITLE_LAUNCH_NEW   " Uruchomic nowe? "
#define L_CORE_FORM_SERVICE_TYPE  "* Typ uslugi <%s> "
#define L_CORE_STATUS_SKIP        " nie wchodzi gdy poprzednie jest jeszcze w kolejce"
#define L_CORE_STATUS_ALWAYS      " wchodzi zawsze do kolejki (wykonuje sie stare i nowe)"
#define L_CORE_STATUS_REPLACE     " wchodzi do kolejki i usuwa poprzednio wstawione "
#define L_CORE_FORM_ORDER_STATUS  "+ Status zlecenia: "
#define L_CORE_TYP_PERM           "p permanentna (stala)"
#define L_CORE_TYP_SERIAL         "s seryjna"
#define L_CORE_TYP_ONESHOT        "t dorazna"
#define L_CORE_TYP_PROMPT         "?  WPISZ TYP !!!!! "
#define L_CORE_FORM_PRIORITY      "+ Priorytet (%d-%d)  ?? "
#define L_CORE_FORM_PRIO_GROWTH   "+ Przyrost prioryt.po 1sek. oczekiwania (%d-%d)  ?? "
#define L_CORE_FORM_CYCLE_PERIOD  "+ Okres cyku wywolan [sek] (%d-%d)  ?? "
#define L_CORE_FORM_NEXT_CALL     " Liczba sek.do najblizszego wywolania  ??"
#define L_CORE_INFO_PERMANENT     " Usluga stala "
#define L_CORE_INFO_CANCELLED     " USLUGA ANULOWANA !!!!! "
#define L_CORE_FORM_NUM_CALLS     " Liczba wywolan  ??"
#define L_CORE_FORM_CALLS_LEFT    " Pozostalo wywolan  "
#define L_CORE_RUN_DATA           "d dane"
#define L_CORE_RUN_NEXT           "n nastepny"
#define L_CORE_RUN_LIST           "l lista"
#define L_CORE_RUN_MAIN_MENU      "m menu glowne"
#define L_CORE_RUN_DELETE         "u USUNAC"
#define L_CORE_RUN_ENTER          "w WPIS do agendy"
#define L_CORE_FORM_WHAT_NEXT     " Co dalej <%s>  ?? "
#define L_CORE_YES_SHORT          "t tak"
#define L_CORE_NO_SHORT           "n nie"
#define L_CORE_FORM_LAUNCH_NEW    " Uruchomic nowe  <%s> ?? "
#define L_CORE_INFO_NO_ALARMS     " Brak budzikow w agendzie "
#define L_CORE_LIST_ROW           " %19S typ=%c prio=%d krotn=%d razy"
#define L_CORE_ERR_OPEN_FILE      "Blad otwarcia pliku"
#define L_CORE_TITLE_ERROR        " BLAD"

/* ===== Admin ===== */
#define L_ADMIN_ERR_ADDR_MISMATCH " Niezgodnosc adresow w RAP_ZM(d=%p dp=%p). <Ent> "
#define L_ADMIN_MENU_BROWSE_LOG   "Przegladanie pliku log.dat"
#define L_ADMIN_MENU_SYS_INFO     "Informacje o systemie"
#define L_ADMIN_MENU_TITLE        " WYBIERZ OPCJE "
#define L_ADMIN_ERR_LOG_OPEN      "+ Blad otwarcia logu: %s"
#define L_ADMIN_LOG_HEADER        "+ --- Log: %s ---"
#define L_ADMIN_SYS_INFO_TITLE    "+ Informacje o systemie"
#define L_ADMIN_SYS_INFO_LINE     "+ System: Linux/Unix (ncurses)"

/* ===== Raporty agendy (sprawdz / sys_rap) ===== */
#define L_RAP_DATE_PREFIX         " Dnia %02d.%02d.%02d "
#define L_RAP_TIME_FMT            "Godz.%02d:%02d.%02d (%s)"
#define L_RAP_DAY_SUNDAY          "Niedziela"
#define L_RAP_DAY_MONDAY          "Poniedzialek"
#define L_RAP_DAY_TUESDAY         "Wtorek"
#define L_RAP_DAY_WEDNESDAY       "Sroda"
#define L_RAP_DAY_THURSDAY        "Czwartek"
#define L_RAP_DAY_FRIDAY          "Piatek"
#define L_RAP_DAY_SATURDAY        "Sobota"
#define L_RAP_ERR_ADDR_SPRAWDZ    " Blad adresu w Sprawdz (A=%p). <Ent> "
#define L_RAP_TITLE_BASIC         "+ Raport zlecen podstawowych SPRAWDZ (jest razem %d)"
#define L_RAP_NO_ORDER_AT_POS     "+ Brak zlecenia na poz.%d w agendzie"
#define L_RAP_MAIN_ORDER          "+ Zlecenie glowne:"
#define L_RAP_LIST_ROW_PRIOR      " %19S typ=%c prior=%d okres=%d"
#define L_RAP_TYP_USL_NO_PREFIX   " Typ uslugi <%s> "
#define L_RAP_PERMANENT_NOREM     "+   Zlecenie stale nieusuwlne !!!! "
#define L_RAP_PERIOD_BR           " Okres wywolan [sek](%d-%d) ?? "
#define L_RAP_TIME_TO_NEXT        " Czas do nastepnego wywolania %dmin %dsek"
#define L_RAP_PRIORITY            " Priorytet (%d-%d) ?? "
#define L_RAP_STATE_PROGRESS      " Stan realizacji "
#define L_RAP_MENU_DATA_ENTRY     "d wpis danych"
#define L_RAP_MENU_ALG_DATA       "a dane algorytmow"
#define L_RAP_MENU_DELETE         "u usuwamy"
#define L_RAP_PROMPT_ACTION       " Co robimy <%s>  ?? "
#define L_RAP_NO_RECORD_SYS       " Brak rekordu w RAP_SYS nr=%d. <Ent> "
#define L_RAP_NO_ORDERS_AGENDA    " Brak zlecen w agendzie "
#define L_RAP_TITLE_PERIODIC      "+ Raport zlecen okresowych w agendzie (jest razem %d)"
#define L_RAP_ORDER_RANGE         "+ Zlec. (%d-%d) "
#define L_RAP_SERVICE_LINE        "+ Usluga: %19s typ=%c prior=%d Cykl=%d Opozn=%5.0f"
#define L_RAP_PERMANENT_SHORT     "  Zlecenie stale !! "
#define L_RAP_NUM_CALLS           " Liczba wywolan  "
#define L_RAP_PERIOD_BR_QQ        " Okres wywolan (%d-%d)  ?? "

/* ===== Konfig (nazwy podsystemów w menu) ===== */
#define L_KONFIG_SRV_SPRAWDZ      " Sprawdz.otoczenia"
#define L_KONFIG_SRV_BUDZIK       " Budzik"
#define L_KONFIG_SRV_ADMIN        " O systemie..."
#define L_KONFIG_SRV_MQTT         " MQTT Publisher"
#define L_KONFIG_SRV_SENSOR       " Czujnik Sim"
#define L_KONFIG_SRV_STAN         " -- Stan systemu --"

/* ===== Czujnik symulowany ===== */
#define L_SIM_WAVE_SINE           "Sinus"
#define L_SIM_WAVE_SQUARE         "Prostokat"
#define L_SIM_WAVE_SAW            "Pila"
#define L_SIM_WAVE_NOISE          "Szum"
#define L_SIM_SERVICE_NAME        "czujnik symulowany"
#define L_SIM_LIVE_READONLY       "+ Podglad na zywo (tylko odczyt)"
#define L_SIM_HEADER              "+ ===== Czujnik Symulowany ====="
#define L_SIM_VALUE               "+  Wartosc  : %d"
#define L_SIM_VALUE2              "+  Wartosc2 : %s"
#define L_SIM_VALUE3              "+  Wartosc3 : %10.4f"
#define L_SIM_MIN_MAX             "+  Min/Max  : %10.4f / %10.4f"
#define L_SIM_SAMPLES             "+  Probki   : %.0f"
#define L_SIM_ALARM_LABEL         "+  Alarm    : %s"
#define L_SIM_ALARM_OK            "OK"
#define L_SIM_ALARM_RANGE         "ZAKRES !!!"
#define L_SIM_ALARM_TIME          "CZAS !!!"
#define L_SIM_FIELD_WAVE          "+ Przebieg        "
#define L_SIM_FIELD_AMP           "+ Amplituda       "
#define L_SIM_FIELD_FREQ          "+ Czestotliwosc   "
#define L_SIM_FIELD_OFFS          "+ Przesuniecie DC "
#define L_SIM_FIELD_TMAX          "+ Prog alarmu MAX "
#define L_SIM_FIELD_TMIN          "+ Prog alarmu MIN "
#define L_SIM_LIST_TITLE          " Lista czujnikow "

/* ===== MQTT Publisher ===== */
#define L_MQTT_MENU_CONNECT       "  >>> Polacz / Zapisz <<<"
#define L_MQTT_MENU_DISCONNECT    "  >>> Rozlacz         <<<"
#define L_MQTT_TITLE              " MQTT PUBLISHER "
#define L_MQTT_STATUS_LINE        "  Status   : %s  (pub:%d  err:%d)"
#define L_MQTT_STATE_CONNECTED    "POLACZONY"
#define L_MQTT_STATE_DISCONNECTED "Rozlaczony"
#define L_MQTT_FIELD_BROKER       "  Broker   : %s"
#define L_MQTT_FIELD_PORT         "  Port     : %d"
#define L_MQTT_FIELD_TOPIC        "  Topic    : %s"
#define L_MQTT_FIELD_NODE_ID      "  Node ID  : %d"
#define L_MQTT_FIELD_QOS          "  QoS      : %d"
#define L_MQTT_FIELD_INTERVAL     "  Interwal : %d s"
#define L_MQTT_PROMPT_BROKER      "Broker"
#define L_MQTT_PROMPT_PORT        "Port"
#define L_MQTT_PROMPT_TOPIC       "Topic"
#define L_MQTT_PROMPT_NODE_ID     "Node ID"
#define L_MQTT_PROMPT_QOS         "QoS"
#define L_MQTT_PROMPT_INTERVAL    "Interwal [s]"
#define L_MQTT_OK_MSG             " Polaczono z %s:%d  (topic: %s/%d/...)"
#define L_MQTT_ERR_MSG            " Blad polaczenia z %s:%d  (err: %d) <Ent>"

/* ===== Wewy (silnik blankietow: hasla, startup, najczestsze bledy) ===== */
/* Hasla / uprawnienia */
#define L_WEWY_SAVE_OR_CANCEL    "  <Ent> - zapis danych; <Esc> - anulowanie zmian: ??     "
#define L_WEWY_ENTER_PASSWORD    " WPISZ HASLO i zatwierdz je <Ent>: ?? "
#define L_WEWY_BAD_PASSWORD_1    " NIEWLASCIWE HASLO: <Ent> - powtorka; <Esc> - wyjscie z anulowaniem zmian: ??  "
#define L_WEWY_BAD_PASSWORD_2    " NIEWLASCIWE HASLO: <Ent> - powtorka; <Esc> - wyjscie z procedury: ??   "
#define L_WEWY_LOW_PERMS_1       "  ZA NISKIE UPRAWNIENIA: <Ent> -powtorka; <Esc> -wyjscie z anulow.zmian ?? "
#define L_WEWY_LOW_PERMS_2       "ZA NISKIE UPRAWNIEN: <Ent> -powtorka; <Esc> -wyjscie z anulowaniem zmian: ?? "
#define L_WEWY_NEED_MAIN_TERM    " Poziom uprawnien %d wymaga TERMINALA GLOWNEGO !! <Ent> "
#define L_WEWY_ONLY_MAIN_TERM    " Zmiany mozna wprowadzic tylko Z TERMINALA GLOWNEGO !! Zostana ANULOWANE. <Ent> "
#define L_WEWY_ASK_PERM_CODE     " Podaj kod uprawn [%s] ?? "
/* Poziomy uprawnien */
#define L_WEWY_PERM_0            "0 tylko pokaz danych"
#define L_WEWY_PERM_1            "1 zapis z termin.glown."
#define L_WEWY_PERM_2            "2 zapis po podaniu hasla"
#define L_WEWY_PERM_3            "3 zapis z term.gl.+haslo"
#define L_WEWY_PERM_4            "4 operator glowny"
#define L_WEWY_PERM_5            "5 oper.glowny i term.gl."
/* Startup sesji */
#define L_WEWY_PREV_REPORTS_OPEN " Nie zamkniete raporty poprzedniej sesji    <Ent>    "
#define L_WEWY_PREV_ALLOCS_LEFT  " Pozostaly alokacje pamieci z poprzedniej sesji (%d) <Ent>  "
#define L_WEWY_NEW_ALLOCS_SESS   " Przybylo alokacji pamieci w tej sesji: bylo %d jest %d <Ent>  "
#define L_WEWY_PREV_BLANKS_OPEN  "Nie zamkniete blankiety (ostatni %d, stan %d) z poprzedniej sesji: <q> - koniec; <d> - dalej ?? "
#define L_WEWY_PREV_REPORT_OPEN  "Nie zamkniety raport %d z poprzedniej sesji: <q> - koniec; <d> - dalej ?? "
/* Najczestsze bledy runtime */
#define L_WEWY_NO_DATA_GENERIC   " Brak danych !! "
#define L_WEWY_NO_REPORT_DATA    " Brak danych raportu %d !!!!!!!!!!!!!!! <Ent> "
#define L_WEWY_NO_REPORT         " Brak raportu %d !!!!!!!!!!!!!!! <Ent> "
#define L_WEWY_NO_REPORTS_OPEN   " Nie otwarte raporty. Uzyj funkcji otworz_raporty() !!!!!  <Ent>    "
#define L_WEWY_REPORT_NO_FREE    " Raport %d nie zwalnia pamieci - alokacja %s(%d) niemozliwa "
#define L_WEWY_ALL_REPORTS       " WSZYSTKIE RAPORTY !!!!!!!   "
/* Prompty / markery */
#define L_WEWY_ENTER_REPLY       "Wpisz odpowiedz na poprzednie pytanie"
#define L_WEWY_ABORT_PROMPT      "   ABORT programu !!! ?? TAK - 't'     "
#define L_WEWY_OUT_OF_RANGE      " ZAKRES !! <ENT>-popraw "
#define L_WEWY_OUT_OF            " poza "
#define L_WEWY_OUT_OF_FMT        " poza%s <ENT> "
#define L_WEWY_MISSING_MARK      " !? "
#define L_WEWY_MISSING_LONG      " Brak !! "
#define L_WEWY_DATA_ENTRY        "  Wpis danej "
#define L_WEWY_BAD_DATA          "Bledna dana (%s) typu %c"
#define L_WEWY_NO_SYNC_TASK      " Brak zadania synchronizowanego z klawiatura !!! <q - exit> "

#endif

#endif /* STUD_SYS_LOC_H */
